[oneAPI_Level_Zero_Headers]
git-tree-sha1 = "7df586204bca0005ee6db3222014b7431716402b"

    [[oneAPI_Level_Zero_Headers.download]]
    sha256 = "d9f3dc18508ba0369f68d66af3460418414984071968b55341accea586998475"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Level_Zero_Headers_jll.jl/releases/download/oneAPI_Level_Zero_Headers-v1.16.0+0/oneAPI_Level_Zero_Headers.v1.16.0.any.tar.gz"
